include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Keep rules minimal and sane for scaffolded project
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
